// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YukiVerse.Api.Data;

#nullable disable

namespace YukiVerse.Api.Migrations
{
    [DbContext(typeof(YukiVerseDbContext))]
    partial class YukiVerseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YukiVerse.Api.Domain.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("platform_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Verdict")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_activity_logs");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_activity_logs_occurred_at");

                    b.HasIndex("PlatformId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_activity_logs_platform_id_external_id")
                        .HasFilter("\"external_id\" IS NOT NULL");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.DailyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("platform_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_daily_activities");

                    b.HasIndex("PlatformId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_activities_platform_id_date");

                    b.ToTable("daily_activities", (string)null);
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_platforms");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_platforms_name");

                    b.ToTable("platforms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "codeforces"
                        },
                        new
                        {
                            Id = 2,
                            Name = "atcoder"
                        },
                        new
                        {
                            Id = 3,
                            Name = "leetcode"
                        },
                        new
                        {
                            Id = 4,
                            Name = "github"
                        });
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.ProblemStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EasySolved")
                        .HasColumnType("integer")
                        .HasColumnName("easy_solved");

                    b.Property<int?>("HardSolved")
                        .HasColumnType("integer")
                        .HasColumnName("hard_solved");

                    b.Property<int?>("MediumSolved")
                        .HasColumnType("integer")
                        .HasColumnName("medium_solved");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("platform_id");

                    b.Property<int>("TotalSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_solved");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_problem_stats");

                    b.HasIndex("PlatformId")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_stats_platform_id");

                    b.ToTable("problem_stats", (string)null);
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.RatingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContestName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contest_name");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("platform_id");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_rating_history");

                    b.HasIndex("PlatformId", "ContestName")
                        .IsUnique()
                        .HasDatabaseName("ix_rating_history_platform_id_contest_name");

                    b.HasIndex("PlatformId", "Date")
                        .HasDatabaseName("ix_rating_history_platform_id_date");

                    b.ToTable("rating_history", (string)null);
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("platform_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sync_logs");

                    b.HasIndex("PlatformId", "LastSyncAt")
                        .HasDatabaseName("ix_sync_logs_platform_id_last_sync_at");

                    b.ToTable("sync_logs", (string)null);
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.ActivityLog", b =>
                {
                    b.HasOne("YukiVerse.Api.Domain.Platform", "Platform")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_platforms_platform_id");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.DailyActivity", b =>
                {
                    b.HasOne("YukiVerse.Api.Domain.Platform", "Platform")
                        .WithMany("DailyActivities")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_activities_platforms_platform_id");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.ProblemStats", b =>
                {
                    b.HasOne("YukiVerse.Api.Domain.Platform", "Platform")
                        .WithMany("ProblemStats")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_stats_platforms_platform_id");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.RatingHistory", b =>
                {
                    b.HasOne("YukiVerse.Api.Domain.Platform", "Platform")
                        .WithMany("RatingHistory")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rating_history_platforms_platform_id");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.SyncLog", b =>
                {
                    b.HasOne("YukiVerse.Api.Domain.Platform", "Platform")
                        .WithMany("SyncLogs")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_logs_platforms_platform_id");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("YukiVerse.Api.Domain.Platform", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("DailyActivities");

                    b.Navigation("ProblemStats");

                    b.Navigation("RatingHistory");

                    b.Navigation("SyncLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
